
// Objective-C API for talking to the following Go packages
//
//	psssign/gomobile_pss_signer
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Signer_FRAMEWORK_H__
#define __Signer_FRAMEWORK_H__

#include "Signer.objc.h"
#include "Universe.objc.h"

#endif
